project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "ZHONG JIAJUN"
  date: "20/01/2026"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd

format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
